steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/whiskyverse:$COMMIT_SHA', '.']

# Push the image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/whiskyverse:$COMMIT_SHA']

# Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'whiskyverse'
  - '--image'
  - 'gcr.io/$PROJECT_ID/whiskyverse:$COMMIT_SHA'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--port'
  - '80'
  - '--cpu'
  - '1'
  - '--memory'
  - '512Mi'
  - '--concurrency'
  - '80'
  - '--max-instances'
  - '10'
  - '--set-env-vars'
  - 'NODE_ENV=production'
  - '--set-env-vars'
  - 'VITE_SUPABASE_URL=${_SUPABASE_URL}'
  - '--set-env-vars'
  - 'VITE_SUPABASE_ANON_KEY=${_SUPABASE_ANON_KEY}'

# Configure the service for custom domain (optional)
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'domain-mappings'
  - 'create'
  - '--domain'
  - '${_DOMAIN}'
  - '--service'
  - 'whiskyverse'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if [[ "${_DOMAIN}" != "" ]]; then
      gcloud run domain-mappings create --domain ${_DOMAIN} --service whiskyverse --region europe-west1 --platform managed || echo "Domain mapping might already exist"
    fi

substitutions:
  _SUPABASE_URL: 'https://your-project.supabase.co'
  _SUPABASE_ANON_KEY: 'your-anon-key'
  _DOMAIN: '' # Set this if you want custom domain

options:
  logging: CLOUD_LOGGING_ONLY